---
- name: install tools
  become: yes
  copy:
    src: "bin/{{ item }}"
    dest: /usr/local/bin
    mode: 0555
  with_items:
    - __fzf-docker-container
    - __fzf-docker-image
    - __fzf-docker-volume
    - argparse
    - git-foreach
    - preview
