version: '3'
services:
  jail:
    image: manabedaiki/devenv:latest
    expose:
      - 22
    ports:
      - ${SSHD_PORT}:22
    volumes:
      - ./id-ed25519.pub:/home/tsuru/.ssh/authorized_keys:ro
      - ./devenv/overlay/home/tsuru/.local/.environment:/home/tsuru/.local/.environment:ro
    command: /usr/sbin/sshd -D
