---
- name: install docker dependencies
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: install GPG key
  become: yes
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add apt repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
  register: docker_add_apt_repository

- name: update apt cache
  become: yes
  apt:
    update_cache: yes
  when: docker_add_apt_repository.changed

- name: install docker
  become: yes
  apt:
    name: docker-ce

- name: append docker group to user
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes

- name: install docker-compose
  become: "{{ become_when_installing_package }}"
  pip:
    name: docker-compose
    executable: "{{ which_pip }}"
    extra_args: --no-cache-dir
