---
- name: install pip
  become: "{{ become_when_installing_package }}"
  package:
    name: "{{ pip_package_name }}"

- name: upgrade pip
  become: "{{ become_when_installing_package }}"
  pip:
    name: pip
    executable: "{{ which_pip }}"
    extra_args: --no-cache-dir --upgrade
