---
- name: install docker dependencies
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: install GPG key
  become: yes
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add apt repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
  register: docker_add_apt_repository

- name: update apt cache
  become: yes
  apt:
    update_cache: yes
  when: docker_add_apt_repository.changed

- name: install docker
  become: yes
  apt:
    name: docker-ce

- name: append docker group to user
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes

- name: has docker-compose?
  stat:
    path: /usr/local/bin/docker-compose
  register: has_docker_compose

- name: install docker-compose
  become: yes
  uri:
    url: https://github.com/docker/compose/releases/download/1.13.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0555
  when: not has_docker_compose.stat.exists
