---
- name: has drone?
  stat:
    path: /usr/local/bin/drone
  register: has_drone

- name: download drone
  uri:
    url: "{{ drone_tar_gz }}"
    dest: /tmp/drone.tar.gz
    mode: 0600
  when: not has_drone.stat.exists

- name: install drone
  become: yes
  unarchive:
    src: /tmp/drone.tar.gz
    dest: /usr/local/bin
    mode: 0555
  when: not has_drone.stat.exists
