---
- include_vars: "{{ ansible_os_family }}.yml"

- include: drone.yml
  when: install_drone

- include: fonts.yml
  when: install_fonts

- include: go.yml
  when: install_go

- include: node.yml
  when: install_node

- include: python.yml
  when: install_python
