---
- name: apt-get update
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - update

- name: apt-get dist-upgrade
  become: yes
  apt:
    upgrade: dist
  tags:
    - update
