---
- name: clean home
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: absent
  with_items:
    - .cache
    - .lesshst
    - .sudo_as_admin_successful
    - .viminfo
    - .zcompdump
