---
- name: create .ssh/config
  template:
    src: config.j2
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    mode: 0400

- name: create .ssh/id
  copy:
    src: "~/.ssh/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.ssh/{{ item }}"
    mode: 0400
  with_items: "{{ ssh_keys }}"
