---
- name: create /usr/local/lib/provisioning-service
  become: yes
  file:
    path: "/usr/local/lib/provisioning-service/{{ item.name }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0700
    state: directory
  with_items:
    - { name: 'dropbox', when: "{{ install_dropbox }}" }
  when:
    - item.when

- name: install templates
  template:
    src: "{{ item.name }}.j2"
    dest: "/usr/local/lib/provisioning-service/{{ item.name }}"
  with_items:
    - { name: 'dropbox/docker-compose.yml', when: "{{ install_dropbox }}" }
  when: item.when
